{% set name = "pyppeteer" %}
{% set version = "0.2.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: c2974be1afa13b17f7ecd120d265d8b8cd324d536a231c3953ca872b68aba4af
  patches:
    - conda-forge.patch

build:
  noarch: python
  number: 0
  entry_points:
    - pyppeteer-install = pyppeteer.command:install
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python >=3.6
    - pip
    - poetry >=0.12
  run:
    - python >=3.6
    - pyee >=7.0.1,<8.0.0a0
    - websockets >=8.1,<9.0.0a0
    - appdirs >=1.4.3,<2.0.0a0
    - urllib3 >=1.25.8,<2.0.0a0
    - tqdm >=4.42.1,<5.0.0a0
    - certifi

test:
  requires:
    - pip
  imports:
    - pyppeteer
  commands:
    - python -m pip check

about:
  home: https://pyppeteer.github.io/pyppeteer
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Headless chrome/chromium automation library (unofficial port of puppeteer)
  doc_url: https://pyppeteer.github.io/pyppeteer
  dev_url: https://github.com/pyppeteer/pyppeteer

extra:
  recipe-maintainers:
    - kiwi0fruit
    - bollwyvl
    - SylvainCorlay
