travis:
  secure:
    BINSTAR_TOKEN: nEv8i7O6H1qmTojyrmoEHl50Kcxch6F1rjNnKRfjkQfMf36j1MXTS76FZgBvlJbA0SQ3M99+uqdNPMnyTQzFP241ZUHkFJcngdWWe+VDw0cnIBoHeWuS4OgJ7jJ8u/uO6ogGn0jHQ+EBMtS62LtVbsI4G+ZGNEL/CZLxANf8T9de1XBTLFoHNsfwU7KEARbnkztZ0/2xAS0kx3djvnVFknV1+ictJ0UgBZznS0zoCW+MwwcTOpjE7ZBjX0wicuTfQK7JYc2JNNrKAavybHrtQ3gP5C9Ae76aPXWHT18N07EcsAyMYeSv1DPCkiN5lKj1lzzei51oUTWZQEdSLlXZ/BQzbPkTunjprQRGcsn1eP6ffw7OUNZreU9SNiU8aEuq0vorJRrDj2VbM3B2SkIn4y0g/vc3nQdER8fetLThAHSd9Ny2tkpcOJucOdp4V7AcArZ3vKy6Q8yMirBzxc2PFP/zNgApeRF4t6/p2vQKM7Du5OtSQ3usmx561pZHNfm7BXOl5IJMVdeKSMPQPtspb82eTVaPlFYdHwalTylWTyBp/gH4qmIhP2nCZB1g612AbywxO+SgYIRx2l6qPq4aVI/NcFsQy7TsSXEc9ir1qoZGA0shnCA5hilRX4kt6HPgs/zcUcomIQGAYODqleLfIlo6pV3jIhmBrS8FUgpsWPE=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
